config/routes.rb
Hacker::Application.routes.draw do
 root to: "links#index"
 resources :links, :except => [:new, :edit] do
  resources :votes, :except => [:new, :edit, :delete]
  resources :comments, :except => [:new, :edit, :delete]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :commentable, :polymorphic => true
    has_many :comments, :as => :commentable
end

app/models/link.rb
require 'pry'
class Link < ActiveRecord::Base
    has_many :votes
    has_many :comments, :as => :commentable
    validates :url, :presence => true

    def self.cal_vote_order
        Link.all.each do |link|
        vote_count = 0
        link.update(:order => 0)
            if link.votes.length != 0
                link.votes.each { |vote| vote_count += vote.vote_status }
                link.update(:order => vote_count)
            end
        end
    end
    def self.cal_date_order
     date = Date.today
        Link.all.each do |link|
            year = (date.year - link.created_at.year)*(12)
            month = (date.month - link.created_at.month)
            total_penalty = year + month
            new_order = link.order - total_penalty
            link.update(:order => new_order)
        end
    end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :link
    validates :link_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    def index
       Link.cal_vote_order
       # Link.cal_date_order
       @links = Link.all

        # params crash

        @link = Link.new
    end
    def create
        @link = Link.new(link_params)
        @link.update(:order => 1)
        if @link.save
            redirect_to "/"
        else
            @links = Link.all
            index
        end
    end
    def show
        @link = Link.find(params[:id])
    end
    def update
        @link = Link.find(params[:id])

        if @link.update(link_params)
            redirect_to links_path
        else
            show
        end
    end
    def destroy
        @link = Link.find(params[:id])
        @link.destroy
        @links = Link.all
        redirect_to links_path
    end

    def link_params
        params.require(:link).permit(:name, :url)
    end
end

app/controllers/votes_controller.rb
class VotesController<ApplicationController
    def create
        @link = Link.find(params[:link_id])
        status_number = params[:vote][:vote_status]
        @vote = Vote.new({:vote_status => status_number})
        @link.votes << @vote

        redirect_to('/')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= render("layouts/errors", :object => @link) %>
<div class="hidden_form">

   <%= form_for(@link) do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name %>
        </div>
        <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url %>
        </div>
        <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, size: "25x7" %>
        </div>
        <%= f.submit(:class => "btn btn-primary") %>
        <% end %>
</div>

app/views/links/index.html.erb
<h1>Mock Hacker News Website<h1>
<hr>

 why don't you work
<ul>
    <%@links.order(order: :desc) .each do |l| %>
        <li><%= link_to l.name, link_path(l) %></li>
    <% end %>
</ul>

<hr>

<button class="new hide_buttons btn-default">New Link</button>

<%= render("form") %>

app/views/links/show.html.erb
<h1><%= @link.name %></h1>
<h2><a href="http://<%=@link.url%>"><%=@link.url%></a></h2>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <%= link_to "Home", links_path, :class => "navbar-brand" %>
    <p class="pull-right navbar-text"><%= @link.name %> </p>
    <div class="btn-group-xs">
        <button type="button" class="new btn btn-default navbar-btn">Edit</button>
        <button type="button" class="btn btn-default navbar-btn">
            <%= link_to "Delete", link_path(@link), :class => "",
                                                    :confirm => "Are you sure?",
                                                    :method => "delete" %></button>
    </div>
</nav>
<hr>

<div class="hidden_form">
    <%= render 'form' %>
</div>


<hr>
<h3>Was This Link Helpful?</h3>

<form action="/links/<%=@link.id%>/votes" method="post">
    <input name="vote[vote_status]" value="1" type="hidden">
    <button class="btn btn-danger">Vote Up</button>
</form><br>

<form action="/links/<%=@link.id%>/votes" method="post">
    <input name="vote[vote_status]" value="-1" type="hidden">
    <button class="btn btn-danger">Vote Down</button>
</form>


<hr>

<p> Put information related to votes here </p>